# This version contains a workaround for the Boost.Unordered file missing issue.
# Specifically, we download boost manually and include the path to $CMAKE_PREFIX_PATH
# so that cmake can find Boost.Unordered header files.
name: CI Test

on:
  push:
  pull_request:
  merge_group:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      CC: gcc-13
      CXX: g++-13
    steps:
      - uses: actions/checkout@v3
      - name: Display versions
        run: |
          cmake --version
          g++ --version
      - name: Install OpenMPI
        run: sudo apt-get install openmpi-bin libopenmpi-dev
      - name: Build and test
        run: |
          cd $GITHUB_WORKSPACE
          mkdir build
          cd build
          cmake ../ -DMETALLDATA_BUILD_TESTS=ON BOOST_FETCH_URL=https://archives.boost.io/release/1.87.0/source/boost_1_87_0.tar.bz2
          make -j6
          make test
      - name: end-to-end testing
        run: |
          cd $GITHUB_WORKSPACE/build
          #python3 -m venv venv
          #source venv/bin/activate
          python3 -m pip install -r ../test/clippy/requirements.txt -r ../test/clippy/requirements-dev.txt
          echo "inspecting"
          which python
          which python3
          make pytest
